### ISSUE TITLE
Module build failed: Error: Cannot find module 'emojis-list'

### ISSUE THREAD

**Issue by absorber** [ddevault/receptor#60]
Hi, I've built receptor from latest git master as instructed. See here: https://paste.debian.net/plain/1148877/

However, once I issue `npm start` and point my browser to http://localhost:3000/, it presents me with a page that has the following error messages:

```
ERROR in ./src/index.js
Module build failed: Error: Cannot find module 'emojis-list'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/me/sources/receptor/node_modules/loader-utils/lib/interpolateName.js:4:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)


ERROR in ./node_modules/style-loader!./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/font-awesome-sass-loader/font-awesome-sass-styles.loader.js!./font-awesome.config.js
Module build failed: Error: Cannot find module 'emojis-list'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/me/sources/receptor/node_modules/loader-utils/lib/interpolateName.js:4:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I'm on Ubuntu 18.04 and my npm is v3.5.2

**Comment by absorber** [comment]
The lovely people over at the JavaScript matrix room (`Internal room ID: !ijKShMHPvuTtGXjrFX:matrix.org`) recommended me to run `npm install emojis-list` inside the root of receptor's git directory. Which I did. And now it works!

I also made a PR in which I added the package to `package.json`
